"""associated u-s u-n n-s

Revision ID: 0421350d9ccf
Revises: 32da0308036f
Create Date: 2022-12-09 11:14:34.506872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0421350d9ccf'
down_revision = '32da0308036f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stoops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('neighborhood_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'neighborhoods', ['neighborhood_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neighborhood_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'neighborhoods', ['neighborhood_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('neighborhood_id')

    with op.batch_alter_table('stoops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('neighborhood_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
