"""add lat and long

Revision ID: 115ed5eda5d7
Revises: 8d82184f89ba
Create Date: 2022-12-12 19:53:02.409755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115ed5eda5d7'
down_revision = '8d82184f89ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stoops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stoops', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
