"""nullable n_id

Revision ID: 8d82184f89ba
Revises: 0421350d9ccf
Create Date: 2022-12-09 13:57:02.965113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d82184f89ba'
down_revision = '0421350d9ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('neighborhood_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('neighborhood_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
